apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filestash-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - filestash.{{ .Values.dns.name }}
    secretName: tls-secret-filestash
  rules:
  - host: filestash.{{ .Values.dns.name }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: filestash
            port:
              number: 8334
